inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/DefEndAlignment:
  EnforcedStyleAlignWith: def

AllCops:
  TargetRubyVersion: 3.0.0
